In [1]:
# Define 2 matrices

In [26]:
import numpy as np
import pandas as pd

In [27]:
X = np.array([[1000,2,1],
             [1200,3,1],
             [1500,3,1],
             [1700,4,1],
             [1900,4,1]])

In [28]:
Y = np.array([200,250,300,360,400])

In [29]:
X.T

array([[1000, 1200, 1500, 1700, 1900],
       [   2,    3,    3,    4,    4],
       [   1,    1,    1,    1,    1]])

In [30]:
result_matrix = np.dot(X.T, X)
result_matrix

array([[11190000,    24500,     7300],
       [   24500,       54,       16],
       [    7300,       16,        5]])

In [31]:
inverse = np.linalg.inv(result_matrix)
inverse

array([[ 1.47368421e-05, -6.00000000e-03, -2.31578947e-03],
       [-6.00000000e-03,  2.80000000e+00, -2.00000000e-01],
       [-2.31578947e-03, -2.00000000e-01,  4.22105263e+00]])

In [32]:
matrix_result = np.dot(inverse, X.T)
matrix_result

array([[ 4.21052632e-04, -2.63157895e-03,  1.78947368e-03,
        -1.26315789e-03,  1.68421053e-03],
       [-6.00000000e-01,  1.00000000e+00, -8.00000000e-01,
         8.00000000e-01, -4.00000000e-01],
       [ 1.50526316e+00,  8.42105263e-01,  1.47368421e-01,
        -5.15789474e-01, -9.78947368e-01]])

In [33]:
matrix = np.dot(matrix_result, Y)
matrix

array([  0.18210526,  18.        , -21.47368421])